version: "3"
services:
  windows:
    container_name: windows
    image: alv67/windows-arm
    #devices:
    #  - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
